name: Dumper-7 Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 拉取项目
        uses: actions/checkout@v4

      - name: 配置 x64 编译器
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: 构建
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64
          dir x64/Release
      - name: 上传构建
        uses: actions/upload-artifact@v3
        with:
          name: Dumper-7.dll
          path: x64/Release/Dumper-7.dll
          retention-days: 7
